### ISSUE TITLE
add custom hudpos

### ISSUE THREAD

**Issue by ByKyTa** [Kxnrl/entWatch#10]
Can you add custom hudpos command !sm_hudpos "x y" 
And add default entwatch_default_hudpos "x y" in entwatch.cfg

**Comment by Kxnrl** [comment]
for each player?

**Comment by ByKyTa** [comment]
yes

**Comment by ByKyTa** [comment]
#include <fys.menu>
#include <fys.bans>	
#include <leader>

where this code ?

**Comment by Kxnrl** [comment]
uploaded files in last commit

**Comment by ByKyTa** [comment]
failed to reload: Native "Opts_IsClientLoaded" was not found.
