### ISSUE TITLE
Add Menu Command In Admin Command

### ISSUE THREAD

**Issue by ByKyTa** [Kxnrl/entWatch#2]
Command open Menu (Admin and Member): sm_ew
Member:
sm_estats
sm_ehud
Admin:
sm_eban
sm_eunban
sm_etransfer
sm_ereload

**Comment by Kxnrl** [comment]
{ sm_eban, sm_eunban, sm_etransfer, sm_ereload } -> sm_admin ?

**Comment by ByKyTa** [comment]
Yes

Vào 20:21 Th 7, 19 thg 5 2018 Kyle <notifications@github.com> đã viết:

**Comment by ByKyTa** [comment]
Server ZE PSE
type !ew
![image](https://user-images.githubusercontent.com/33537916/46915360-d518f880-cfd4-11e8-9c0c-2285146bb500.png)

**Comment by ByKyTa** [comment]
@Kxnrl 
Can you update countdown skill  in scoreboard ? And EntWatch Menu In !settings (member)
![image](https://user-images.githubusercontent.com/33537916/52110963-e2fe9200-2634-11e9-985b-4fb95563a0d8.png)

**Comment by ByKyTa** [comment]
Fullscreen 1920*1080 (16:9). How to  word Human(Zombie) Entwatch in top screen ?
![image](https://user-images.githubusercontent.com/33537916/52112223-738aa180-2638-11e9-9a5c-9b30ed44d235.png)

**Comment by ByKyTa** [comment]
entwatch_2017.vmt Can you change Chinese name to English "player skill"

**Comment by ByKyTa** [comment]
@Kxnrl Added Features
Trigger support

Source: https://github.com/Obuss/entWatch

**Comment by Kxnrl** [comment]
I released entwatch2, but you need to make some changes.

**Comment by Kxnrl** [comment]
https://github.com/Kxnrl/entWatch/commit/fd790943dc89ce9f091a4a100d32da12bed7f930
