### ISSUE TITLE
Help cooldown

### ISSUE THREAD

**Issue by ByKyTa** [Kxnrl/entWatch#3]
This plugins is good. But auto create auto cooldown "0" and how i know time cooldown set time ?

**Comment by Kxnrl** [comment]
on m_iOnPressed

**Comment by ByKyTa** [comment]
i don't understand your mean

**Comment by Kxnrl** [comment]
does not wokr on some map. i will keep to find other solutions.

**Comment by Kxnrl** [comment]
feature had been added.
