### ISSUE TITLE
add random colour

### ISSUE THREAD

**Issue by ByKyTa** [Kxnrl/entWatch#4]
Can you add random auto create colour skill when it drop?

**Comment by Kxnrl** [comment]
what do you mean?

**Comment by ByKyTa** [comment]
![image](https://user-images.githubusercontent.com/33537916/41725713-b00af71c-759a-11e8-9749-4a283fd79613.png)

**Comment by Kxnrl** [comment]
color for weapon glow?

**Comment by ByKyTa** [comment]
yes and color name skill

**Comment by Kxnrl** [comment]
No, The impassable color has different meanings.
Green: Item available.
Purple: Item in cooldown.
Red: Item unavailable.
