### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by ByKyTa** [Kxnrl/entWatch#6]
L 09/25/2018 - 22:06:04: [SM] Blaming: zombiereloaded.smx
L 09/25/2018 - 22:06:04: [SM] Call stack trace:
L 09/25/2018 - 22:06:04: [SM]   [0] ThrowNativeError
L 09/25/2018 - 22:06:04: [SM]   [1] Line 91, zr/api/api.inc::APIValidateClientIndex
L 09/25/2018 - 22:06:04: [SM]   [2] Line 68, zr/api/infect.api.inc::APIIsClientZombie
L 09/25/2018 - 22:06:04: [SM]   [4] ZR_IsClientZombie
L 09/25/2018 - 22:06:04: [SM]   [5] Line 2052, entWatch_kyle.sp::IsInfector
L 09/25/2018 - 22:06:04: [SM]   [6] Line 1205, entWatch_kyle.sp::RefreshHud
L 09/25/2018 - 22:06:04: [SM]   [7] Line 1179, entWatch_kyle.sp::Timer_Cooldowns

**Comment by Kxnrl** [comment]
did you compile with latest smutils?

**Comment by ByKyTa** [comment]
yes i using latest smutils

**Comment by Kxnrl** [comment]
Fix it in latest commit
