### ISSUE TITLE
Some issues with entwatch

### ISSUE THREAD

**Issue by cytrus224** [Kxnrl/entWatch#7]
- you can't pickup any weapons on ze_FFVII_Mako_Reactor_v5_3_v5, ze_lotr_minas_tirith_p5, when i disable entwatch, i can pick up weapons again.
- you can only transfer items to yourself, would be nice if we could transfer items to other players, not only admin themselves
- theres only 1h/1d/1w eban options, would be nice if we also had permament eban.
- no entwatch menu in !admin menu

**Comment by Kxnrl** [comment]
- configs have not been tested yet
- emm, i removed transfer to other players before. maybe will add back.
- https://github.com/Kxnrl/entWatch/blob/master/entWatch.sp#L1548
- WIP

**Comment by cytrus224** [comment]
Also, not sure if thats related to entWatch, but when i pick up some items, which change playermodel, sometimes server crashes. f.e. westersand v7 z9

**Comment by Kxnrl** [comment]
entwatch does not hook on player model.

**Comment by cytrus224** [comment]
L 01/15/2019 - 23:13:35: [SM] Exception reported: Weapon 110 is not owned by client 7
L 01/15/2019 - 23:13:35: [SM] Blaming: entWatch.smx
L 01/15/2019 - 23:13:35: [SM] Call stack trace:
L 01/15/2019 - 23:13:35: [SM]   [0] SDKHooks_DropWeapon
L 01/15/2019 - 23:13:35: [SM]   [1] Line 568, entWatch.sp::DropClientEnt
L 01/15/2019 - 23:13:35: [SM]   [2] Line 543, entWatch.sp::ZR_OnClientInfected
L 01/15/2019 - 23:13:35: [SM]   [4] Call_Finish
L 01/15/2019 - 23:13:35: [SM]   [5] Line 180, src\zr/api/infect.api.inc::APIOnClientInfected
L 01/15/2019 - 23:13:35: [SM]   [6] Line 853, src\zr/infect.inc::InfectHumanToZombie
L 01/15/2019 - 23:13:35: [SM]   [7] Line 610, src\zr/infect.inc::InfectMotherZombie

**Comment by Kxnrl** [comment]
Did you use any weapon cleaner plugin?

**Comment by cytrus224** [comment]
No, i dont use any weapon cleaner

**Comment by Kxnrl** [comment]
u need to edit your zr. change strip weapon function. u need strip weapon after ZR_OnClientInfected called.
