### ISSUE TITLE
Zombie Can't Pick Skill 

### ISSUE THREAD

**Issue by ByKyTa** [Kxnrl/entWatch#8]
![20190310150118_1](https://user-images.githubusercontent.com/33537916/54082294-96019000-4345-11e9-8641-1013446a0572.jpg)

**Comment by ByKyTa** [comment]
"[CSGO] entWatch" (1.3.3) by Kyle
File config map
[ze_ffvii_cosmo_canyon_v4fix_ps4.cfg.txt](https://github.com/Kxnrl/entWatch/files/2949208/ze_ffvii_cosmo_canyon_v4fix_ps4.cfg.txt)

**Comment by Kxnrl** [comment]
make sure config
