### ISSUE TITLE
glow weapon

### ISSUE THREAD

**Issue by zeddy1234** [Kxnrl/entWatch#9]
Hey, the entwatch weapon don't glow like it did in my previous entwatch plugin.

Can you make that possible? I already tried mp_weapons_glow_on_ground 1 command , but map weapon don't glow with it.

**Comment by ByKyTa** [comment]
His code default glow "true" but it doesn't work very well
![image](https://user-images.githubusercontent.com/33537916/59266952-27e5a580-8c73-11e9-9920-98964f90fa0c.png)
